language: node_js

node_js:
  - "16"

services:
  - docker

before_install:
  - npm i -g @quasar/cli
  - npm install
  - quasar build

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t kalan4ik/skiog-front .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: main